apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-fe
  namespace: argocd
spec:
  sources:
    - repoURL: https://github.com/dkrish194/to-do-list-k8-helm.git
      targetRevision: main
      path: helm-fe
      helm:
        releaseName: helm-fe-release
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
